server:
  port: 8080

spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:${JWT_SECRET:change-me-change-me-change-me-32-bytes!}}
    expiration-ms: 3600000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080}

routes:
  paths:
    solicitud:
      path: "/api/v1/solicitud"
    tipo:
      path: "/api/v1/tipo"
    estado:
      path: "/api/v1/estado"

# ---- BBDD (tu config adaptador R2DBC) ----
adapters:
  r2dbc:
    host: ${DB_HOST:db-solicitudes}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:solicitudes}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:1234}}

# ---- WebClient (COINCIDE con RestConsumerConfig) ----
adapter:
  http:
    timeout: 5000
  # ambos WebClient usan la misma base URL, tomada de USUARIOS_URL o por defecto usuarios:8081
  restconsumer:
    url: ${USUARIOS_URL:http://usuarios:8081}
    uri:
      validaruser: "/api/v1/validaruser"
  userpaginable:
    url: ${USUARIOS_URL:http://usuarios:8081}
    uri:
      paginable: "/api/v1/solicitud"
